### ISSUE TITLE
Don't publish 3.0.0-beta-001 as stable yet

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-promise#18]
@alfonsogarciacaro 

When upgrading to version 3.0.0-beta-001 in my project, it make Fable compilation fails.

> C:/Users/mamangel/Documents/Workspace/Gitlab/fleet-view/fleet-mapping/Medio/Server/Tests/fableBuild/.fable/Fable.Fetch.2.1.0/Fetch.fs(351,12): (351,23) error FSHARP: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. (code 72)

Yes, the error in Fetch.fs and not fable-promise but that's actually fable-promise which make it fails because if I everything works fine.

Also, when compiling the project via `dotnet build` I don't have the error so I still trying to find the source of the error.

**Comment by MangelMaxime** [comment]
The problem seems like `Promise.map` doesn't infer the parameter type when compile using Fable even if `dotnet` does.

For example, we need to write:

```diff
/// Retrieves data from the specified resource. Fails if `response.Ok` evals to false.
let fetch (url: string) (init: RequestProperties list) : JS.Promise<Response> =
    GlobalFetch.fetch(RequestInfo.Url url, requestProps init)
-    |> Promise.map (fun response ->
+    |> Promise.map (fun (response : Response) ->
        if response.Ok
        then response
        else errorString response |> failwith)
```

This is a problem because type inference doesn't work anymore.

**Comment by MangelMaxime** [comment]
Ok version 3.0.0-beta-002 fixed it.

**Comment by alfonsogarciacaro** [comment]
Ups, my bad. Thanks a lot for fixing!
