### ISSUE TITLE
Why rename Promise.all to Promise.Parallel ?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-promise#2]
`Promise.Parallel` is an alias to `promise.all` in JavaScript [Source](https://github.com/fable-compiler/fable-promise/blob/master/src/Promise.fs#L64-L65). Why not name it `all` directly, especially when we need to name it `Parallel` with an upper `P` in order to avoid F# warning.

**Comment by alfonsogarciacaro** [comment]
I don't really remember if there was a specific reason besides emulating `Async.Parallel`. It's probably OK to add another function named `all` and keep both as aliases.
