### ISSUE TITLE
Release 3.0.0 as stable

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-promise#20]
@alfonsogarciacaro Are we ready to publish the beta version as stable?

**Comment by alfonsogarciacaro** [comment]
I guess so, let me try it in another project of mine to make sure there are no issues and we can release the stable one :+1:

**Comment by alfonsogarciacaro** [comment]
Sorry, I was in the middle of a PR and the project was not in a working state. I tried now with 3.0.0-beta and I had a few errors like:

```
A unique overload for method 'Source' could not be determined based on type information prior to this program point. A type annotation may be needed
```

After adding the type annotation (I hope this is not too annoying for other users) everything seemed to work, so I guess it's fine to publish a stable release :+1:
