### ISSUE TITLE
Update to 3.1.1 is creating compile error

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-promise#26]
FSC : error FS0193: Das Modul bzw. der Namespace "Promise" aus der Kompilierungseinheit "Fable.Promise" enthielt nicht den Wert "ValLinkagePartialKey(Run)". [/home/gitlab-runner/builds/d5cd2d2a/0/a-team/eCarApp/src/Client/Client.fsproj]

Sorry for german error message. It says it can't find `ValLinkagePartialKey`

**Comment by alfonsogarciacaro** [comment]
Oh, my. Didn't even know that 3.1.1. I did some cleanup [here](https://github.com/fable-compiler/fable-promise/commit/651caeb0c27e8af059314347c2e5857346551d17) that wasn't released until now but not sure if related. Googling `ValLinkagePartialKey` returns results about weird F# dependency issues, including [this one](https://github.com/thoth-org/Thoth.Json/issues/45) (maybe @MangelMaxime knows more?).

Are you using Visual Studio? Is this Server/Client shared code? Is this Fable or just building the project with dotnet? If Fable, which version?

**Comment by forki** [comment]
> Are you using Visual Studio? 

hell no. :P 

> is this Server/Client shared code? Is this Fable or just building the project with dotnet?

yes it's probably in shared code path. But can't really tell since it's no showing line number.

**Comment by MangelMaxime** [comment]
Did I already said, that I hate .NET or not ?

I think I know the cause, once again I decided to rename some variable in the function to have a better meaning but .NET is *** and complains about it...

This is stuff like that which caused the breaking:

https://github.com/fable-compiler/fable-promise/commit/84c6edda9e3d5a2594ea539e400268e892d74376#diff-62b7bd88d3dd7d91240f86ab8832fb81eebe3020fcc78887568c88533d957872L29-R149

See how `a` is renamed `mapper`.

So we have two solutions I think:

1. Revert to the old variable names which are not useful and don't provide good documentation... and hope that this fix the problem
2. Keep the new names but republish the libraries depending on fable-promise

**Comment by MangelMaxime** [comment]
The 3.1.1 released was to include the doc comments which allows us to have the API documentation auto generated via Nacara.

![image](https://user-images.githubusercontent.com/4760796/139699747-88dc9905-aa0f-483a-b5c5-42d50fcabf4c.png)

[Live website](https://fable.io/fable-promise/reference/Fable.Promise/global-promise.html#map)

If I don't rename the variable we would generate `a : 'T1 -> 'T2` instead of `mapper ...`

**Comment by alfonsogarciacaro** [comment]
Thanks for the explanations @MangelMaxime!

I can see this line in the F# compiler, it's about a cache: https://github.com/dotnet/fsharp/blob/85fe2809db9c106d3c630c74dbe806eb8b9b09c9/src/fsharp/TypedTree.fs#L1892

Could it happen that the F# compiler is caching the symbol and it breaks with the variable name change? @forki Can you please try cleaning (removing `obj` folder) and compiling again?

**Comment by alfonsogarciacaro** [comment]
FWIW I tried updating one project to Fable.Promise 3.1.1 and didn't see any issue.

**Comment by MangelMaxime** [comment]
> FWIW I tried updating one project to Fable.Promise 3.1.1 and didn't see any issue.

I think that you can have this error only if you are using a library that is depending on Fable.Promise. Also, I am not sure if Fable have this error or only if you do `dotnet build` against the project.

**Comment by forki** [comment]
Cleaning `obj` does not help. 

>> I think that you can have this error only if you are using a library that is depending on Fable.Promise

We have a couple of those.

Fable.I18Next
Fable.Fetch
Thoth.Fetch
Thoth.Elmish.Debouncer

**Comment by MangelMaxime** [comment]
I will revert the arguments name changes and hope that it will fix the problem.

If it doesn't, we will need to re-publish all the packaga that depends on it.

**Comment by MangelMaxime** [comment]
I just released 3.1.2 can you please give it a try when it is available (after indexing)?

@forki

**Comment by alfonsogarciacaro** [comment]
Thanks for this @MangelMaxime! In any case, this seems to be an issue with the F# compiler, I've reported it in the dotnet/fsharp repo.

**Comment by MangelMaxime** [comment]
Thank you for reporting this bug @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
After Don's explanations it seems the problem was caused by my changes in #25 and not by @MangelMaxime renaming some arguments 😅 I've reverted #25, publish 3.1.3 and unlisted 3.1.1, 3.1.2 from Nuget. Hopefully this fixes things.

> I haven't renamed the arguments just in case, but in principle it should be ok to do it. BTW @MangelMaxime I found a link that points to localhost even after publishing documentation to fable.io, is this a Nacara issue?

![image](https://user-images.githubusercontent.com/8275461/140665151-7e80d6ab-96ac-4eae-8f05-8d965f081a90.png)

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro The link issue was just a bad copy/paste on my side.

https://github.com/fable-compiler/fable-promise/commit/5e41fb34ff59eda1b4e4bf8be389bd70038554c0
