### ISSUE TITLE
What happened to Promise signatures ?

### ISSUE THREAD

**Issue by vbfox** [fable-compiler/fable-promise#4]
### Description

While trying to port Ionide to Fable2 (Still with Fable.Core 2 but 3 seem to have the same problem) I remarked that the signatures of methods of `Promise` that were previously correct are now missing a big chunk of the functionalities.

### Repro code

Let's read [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then) and see what `Promise.then` handlers can do:

> * returns a value, the promise returned by then gets resolved with the returned value as its value;
> * doesn't return anything, the promise returned by then gets resolved with an undefined value;
> * returns an already fulfilled promise, the promise returned by then gets fulfilled with that promise's value as its value;

Ok Fable exposes the javascript API, so given the documentation I wound expect that handlers are `'TBefore -> U3<unit, 'TResult, PromiseLike<'TResult>>` but that's not the case:

```fsharp
    and [<AllowNullLiteral>] Promise<'T> =
        abstract ``then``: ?onfulfilled: ('T->'TResult) * ?onrejected: (obj->'TResult) -> Promise<'TResult>
```

### Expected and actual results

Expected: Being able to use JS Api in a typed way
Actual: `unbox`, `unbox`, `unbox`

### Related information

* Fable version: 2.3.7
* Fable.Core: 2.0.3
* Operating system: Windows 10

**Comment by MangelMaxime** [comment]
> Both parameters can have the 2 forms resulting in 4 overloads

In general, I am fine with that personally.

> (I don't have any problem sending a PR btw I didn't do that mainly because I saw so much change that I couldn't well understand breaking things that worked before that I prefered discussing it before)

No worry, most of the changes were made by @alfonsogarciacaro so we wait for his answer perhaps that's just a mistake on our side :)

**Comment by alfonsogarciacaro** [comment]
Sorry, totally missed this issue :/ If you can send a PR to clean up the signatures please definitely do it. I don't remember changing any signature when moving Promise to its own package, but it's true the current status is a bit messy, the result of multiple contributions with different ideas. For example, `Promise.either` tries to cover all possibilities in JS, but it becomes a bit cumbersome to use in F#: https://github.com/fable-compiler/fable-promise/blob/e96a1ba7db446d1f12360fbc451814a32dac98a1/src/Promise.fs#L47-L52

In general I would say try to make things idiomatic in F# and provide an alternative with a different signature when necessary. But there are still some tricky parts, for example the `onFail` continuation is not consistent across the API. Most times it accepts an `Exception` parameter which should cover 99% of cases (System.Exception translates to JS `Error`). However, in JS it's possible to throw something that's not an error and a few signatures acknowledge this by using a generic parameter instead (which forces user to make the argument type explicit in the `onFail` continuation).

**Comment by baronfel** [comment]
~~I ran into this today while trying to update ionide to latest fable (at last!) I also wonder how 'generous' we should be with the typings, being that almost everything promise-related should instead take a 'PromiseLike<'t>` for maximum campatibility?~~ I have since reread the library and it does exactly what I need it to. Thanks!

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I think we can close this issue now. 

It is kind of old and also we changed/improved the Promise signature in Fable.Promise 3.0.0
