### ISSUE TITLE
Using Fable.Promise with Fable.SimpleJson causes fable compiler error

### ISSUE THREAD

**Issue by ThisFunctionalTom** [fable-compiler/fable-promise#50]
We were trying to update packages in Fable.SignalR and came across the following problem.

If only Fable.SimpleJson is used everything compiles fine, but as soon as Fable.Promise is added as nuget package the compilation fails with following output:

```
Fable 4.1.4: F# to JavaScript compiler
Minimum fable-library version (when installed from npm): 1.1.1

Thanks to the contributor! @cmeeren
Stand with Ukraine! https://standwithukraine.com.ua/

Parsing TestSimpleJson.fsproj...
.> cmd /C dotnet restore TestSimpleJson.csproj -p:FABLE_COMPILER=true -p:FABLE_COMPILER_4=true -p:FABLE_COMPILER_JAVASCRIPT=true
  Determining projects to restore...
  Restored C:\Users\leko.tomas\playground\TestSimpleJson\TestSimpleJson.csproj (in 207 ms).
Project and references (12 source files) parsed in 3833ms

Started Fable compilation...
Fable compilation finished in 3523ms

.\fable_modules\Fable.SimpleJson.3.24.0\SimpleJson.fs(6,12): (6,18) error FSHARP: The namespace 'Import' is not defined. (code 39)
Compilation failed
```

Here is a smallest repro I could make. [TestSimpleJson](https://github.com/ThisFunctionalTom/TestSimpleJson)
* clone the repo
* `dotnet tool restore`
* `dotnet fable .`

We already found a similar issue [here](https://github.com/Zaid-Ajaj/Fable.SimpleJson/issues/96), but we couldn't find solution for this problem.

**Comment by MangelMaxime** [comment]
Hello,

The problem is because Fable.SimpleJson is opening `Fable.Import` module but that module doesn't exist anymore.

https://github.com/Zaid-Ajaj/Fable.SimpleJson/blob/master/src/SimpleJson.fs#L6

You need to ask Fable.SimpleJson to upgrade to a newest version of Fable.Core.
